name: Release Documentation

permissions: write-all

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build_docs:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - name: Pull repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Cache executed notebooks
        uses: actions/cache@v3
        with:
          path: docs/_build/.jupyter_cache
          key: jupyter-book-cache-${{ hashFiles('pyproject.toml') }}

      - name: Build docs
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.27.1
          locked: true
          cache: true
      - run: pixi run -e doc build

      - name: Upload HTML as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/_build/html"

      - name: Deploy HTML to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
